/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaItemResponse
 */
export interface MediaItemResponse {
    /**
     * 
     * @type {string}
     * @memberof MediaItemResponse
     */
    mediaItemId: string;
    /**
     * 
     * @type {string}
     * @memberof MediaItemResponse
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof MediaItemResponse
     */
    filename: string;
}

/**
 * Check if a given object implements the MediaItemResponse interface.
 */
export function instanceOfMediaItemResponse(value: object): value is MediaItemResponse {
    if (!('mediaItemId' in value) || value['mediaItemId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    return true;
}

export function MediaItemResponseFromJSON(json: any): MediaItemResponse {
    return MediaItemResponseFromJSONTyped(json, false);
}

export function MediaItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaItemId': json['mediaItemId'],
        'url': json['url'],
        'filename': json['filename'],
    };
}

export function MediaItemResponseToJSON(json: any): MediaItemResponse {
    return MediaItemResponseToJSONTyped(json, false);
}

export function MediaItemResponseToJSONTyped(value?: MediaItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaItemId': value['mediaItemId'],
        'url': value['url'],
        'filename': value['filename'],
    };
}

