/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoContent
 */
export interface NoContent {
    /**
     * 
     * @type {number}
     * @memberof NoContent
     */
    statusCode?: number;
}

/**
 * Check if a given object implements the NoContent interface.
 */
export function instanceOfNoContent(value: object): value is NoContent {
    return true;
}

export function NoContentFromJSON(json: any): NoContent {
    return NoContentFromJSONTyped(json, false);
}

export function NoContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoContent {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function NoContentToJSON(json: any): NoContent {
    return NoContentToJSONTyped(json, false);
}

export function NoContentToJSONTyped(value?: NoContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
    };
}

