/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NullableOfVoteDirection = {
    Up: 'Up',
    Down: 'Down'
} as const;
export type NullableOfVoteDirection = typeof NullableOfVoteDirection[keyof typeof NullableOfVoteDirection];


export function instanceOfNullableOfVoteDirection(value: any): boolean {
    for (const key in NullableOfVoteDirection) {
        if (Object.prototype.hasOwnProperty.call(NullableOfVoteDirection, key)) {
            if (NullableOfVoteDirection[key as keyof typeof NullableOfVoteDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NullableOfVoteDirectionFromJSON(json: any): NullableOfVoteDirection {
    return NullableOfVoteDirectionFromJSONTyped(json, false);
}

export function NullableOfVoteDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableOfVoteDirection {
    return json as NullableOfVoteDirection;
}

export function NullableOfVoteDirectionToJSON(value?: NullableOfVoteDirection | null): any {
    return value as any;
}

export function NullableOfVoteDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): NullableOfVoteDirection {
    return value as NullableOfVoteDirection;
}

