/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagPostResponse
 */
export interface TagPostResponse {
    /**
     * 
     * @type {string}
     * @memberof TagPostResponse
     */
    tagId: string;
    /**
     * 
     * @type {string}
     * @memberof TagPostResponse
     */
    tag: string;
}

/**
 * Check if a given object implements the TagPostResponse interface.
 */
export function instanceOfTagPostResponse(value: object): value is TagPostResponse {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function TagPostResponseFromJSON(json: any): TagPostResponse {
    return TagPostResponseFromJSONTyped(json, false);
}

export function TagPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tagId': json['tagId'],
        'tag': json['tag'],
    };
}

export function TagPostResponseToJSON(json: any): TagPostResponse {
    return TagPostResponseToJSONTyped(json, false);
}

export function TagPostResponseToJSONTyped(value?: TagPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tagId': value['tagId'],
        'tag': value['tag'],
    };
}

