/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCommentRequest
 */
export interface UpdateCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCommentRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommentRequest
     */
    commentId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommentRequest
     */
    body: string;
}

/**
 * Check if a given object implements the UpdateCommentRequest interface.
 */
export function instanceOfUpdateCommentRequest(value: object): value is UpdateCommentRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function UpdateCommentRequestFromJSON(json: any): UpdateCommentRequest {
    return UpdateCommentRequestFromJSONTyped(json, false);
}

export function UpdateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'commentId': json['commentId'],
        'body': json['body'],
    };
}

export function UpdateCommentRequestToJSON(json: any): UpdateCommentRequest {
    return UpdateCommentRequestToJSONTyped(json, false);
}

export function UpdateCommentRequestToJSONTyped(value?: UpdateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'commentId': value['commentId'],
        'body': value['body'],
    };
}

