/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCommentRequest
 */
export interface AddCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    body: string;
}

/**
 * Check if a given object implements the AddCommentRequest interface.
 */
export function instanceOfAddCommentRequest(value: object): value is AddCommentRequest {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function AddCommentRequestFromJSON(json: any): AddCommentRequest {
    return AddCommentRequestFromJSONTyped(json, false);
}

export function AddCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'userId': json['userId'],
        'body': json['body'],
    };
}

export function AddCommentRequestToJSON(json: any): AddCommentRequest {
    return AddCommentRequestToJSONTyped(json, false);
}

export function AddCommentRequestToJSONTyped(value?: AddCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'userId': value['userId'],
        'body': value['body'],
    };
}

