/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAdminBooksPostRequestRating
 */
export interface ApiAdminBooksPostRequestRating {
}

/**
 * Check if a given object implements the ApiAdminBooksPostRequestRating interface.
 */
export function instanceOfApiAdminBooksPostRequestRating(value: object): value is ApiAdminBooksPostRequestRating {
    return true;
}

export function ApiAdminBooksPostRequestRatingFromJSON(json: any): ApiAdminBooksPostRequestRating {
    return ApiAdminBooksPostRequestRatingFromJSONTyped(json, false);
}

export function ApiAdminBooksPostRequestRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAdminBooksPostRequestRating {
    return json;
}

export function ApiAdminBooksPostRequestRatingToJSON(json: any): ApiAdminBooksPostRequestRating {
    return ApiAdminBooksPostRequestRatingToJSONTyped(json, false);
}

export function ApiAdminBooksPostRequestRatingToJSONTyped(value?: ApiAdminBooksPostRequestRating | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

