/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArcadeStatsResponse
 */
export interface ArcadeStatsResponse {
    /**
     * 
     * @type {string}
     * @memberof ArcadeStatsResponse
     */
    game: string;
    /**
     * 
     * @type {number}
     * @memberof ArcadeStatsResponse
     */
    bestScore: number;
    /**
     * 
     * @type {number}
     * @memberof ArcadeStatsResponse
     */
    gamesPlayed: number;
    /**
     * 
     * @type {number}
     * @memberof ArcadeStatsResponse
     */
    rank: number | null;
}

/**
 * Check if a given object implements the ArcadeStatsResponse interface.
 */
export function instanceOfArcadeStatsResponse(value: object): value is ArcadeStatsResponse {
    if (!('game' in value) || value['game'] === undefined) return false;
    if (!('bestScore' in value) || value['bestScore'] === undefined) return false;
    if (!('gamesPlayed' in value) || value['gamesPlayed'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function ArcadeStatsResponseFromJSON(json: any): ArcadeStatsResponse {
    return ArcadeStatsResponseFromJSONTyped(json, false);
}

export function ArcadeStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArcadeStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'game': json['game'],
        'bestScore': json['bestScore'],
        'gamesPlayed': json['gamesPlayed'],
        'rank': json['rank'],
    };
}

export function ArcadeStatsResponseToJSON(json: any): ArcadeStatsResponse {
    return ArcadeStatsResponseToJSONTyped(json, false);
}

export function ArcadeStatsResponseToJSONTyped(value?: ArcadeStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game': value['game'],
        'bestScore': value['bestScore'],
        'gamesPlayed': value['gamesPlayed'],
        'rank': value['rank'],
    };
}

