/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorPostResponse
 */
export interface AuthorPostResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    biography?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorPostResponse
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthorPostResponse
     */
    createdOnUtc?: Date;
}

/**
 * Check if a given object implements the AuthorPostResponse interface.
 */
export function instanceOfAuthorPostResponse(value: object): value is AuthorPostResponse {
    return true;
}

export function AuthorPostResponseFromJSON(json: any): AuthorPostResponse {
    return AuthorPostResponseFromJSONTyped(json, false);
}

export function AuthorPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'createdOnUtc': json['createdOnUtc'] == null ? undefined : (new Date(json['createdOnUtc'])),
    };
}

export function AuthorPostResponseToJSON(json: any): AuthorPostResponse {
    return AuthorPostResponseToJSONTyped(json, false);
}

export function AuthorPostResponseToJSONTyped(value?: AuthorPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'userName': value['userName'],
        'biography': value['biography'],
        'avatarUrl': value['avatarUrl'],
        'createdOnUtc': value['createdOnUtc'] == null ? undefined : ((value['createdOnUtc']).toISOString()),
    };
}

