/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookAuthorResponse
 */
export interface BookAuthorResponse {
    /**
     * 
     * @type {string}
     * @memberof BookAuthorResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookAuthorResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof BookAuthorResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BookAuthorResponse
     */
    nameEn: string | null;
}

/**
 * Check if a given object implements the BookAuthorResponse interface.
 */
export function instanceOfBookAuthorResponse(value: object): value is BookAuthorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nameEn' in value) || value['nameEn'] === undefined) return false;
    return true;
}

export function BookAuthorResponseFromJSON(json: any): BookAuthorResponse {
    return BookAuthorResponseFromJSONTyped(json, false);
}

export function BookAuthorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookAuthorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'nameEn': json['nameEn'],
    };
}

export function BookAuthorResponseToJSON(json: any): BookAuthorResponse {
    return BookAuthorResponseToJSONTyped(json, false);
}

export function BookAuthorResponseToJSONTyped(value?: BookAuthorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'nameEn': value['nameEn'],
    };
}

