/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookSeriesInfo
 */
export interface BookSeriesInfo {
    /**
     * 
     * @type {string}
     * @memberof BookSeriesInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookSeriesInfo
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof BookSeriesInfo
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof BookSeriesInfo
     */
    volumeNumber: number;
}

/**
 * Check if a given object implements the BookSeriesInfo interface.
 */
export function instanceOfBookSeriesInfo(value: object): value is BookSeriesInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('volumeNumber' in value) || value['volumeNumber'] === undefined) return false;
    return true;
}

export function BookSeriesInfoFromJSON(json: any): BookSeriesInfo {
    return BookSeriesInfoFromJSONTyped(json, false);
}

export function BookSeriesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookSeriesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'volumeNumber': json['volumeNumber'],
    };
}

export function BookSeriesInfoToJSON(json: any): BookSeriesInfo {
    return BookSeriesInfoToJSONTyped(json, false);
}

export function BookSeriesInfoToJSONTyped(value?: BookSeriesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'volumeNumber': value['volumeNumber'],
    };
}

