/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookGenreResponse
 */
export interface BookGenreResponse {
    /**
     * 
     * @type {string}
     * @memberof BookGenreResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookGenreResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof BookGenreResponse
     */
    name: string;
}

/**
 * Check if a given object implements the BookGenreResponse interface.
 */
export function instanceOfBookGenreResponse(value: object): value is BookGenreResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BookGenreResponseFromJSON(json: any): BookGenreResponse {
    return BookGenreResponseFromJSONTyped(json, false);
}

export function BookGenreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookGenreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
    };
}

export function BookGenreResponseToJSON(json: any): BookGenreResponse {
    return BookGenreResponseToJSONTyped(json, false);
}

export function BookGenreResponseToJSONTyped(value?: BookGenreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
    };
}

