/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookResponse } from './BookResponse';
import {
    BookResponseFromJSON,
    BookResponseFromJSONTyped,
    BookResponseToJSON,
    BookResponseToJSONTyped,
} from './BookResponse';

/**
 * 
 * @export
 * @interface BooksPageResponse
 */
export interface BooksPageResponse {
    /**
     * 
     * @type {Array<BookResponse>}
     * @memberof BooksPageResponse
     */
    items: Array<BookResponse>;
    /**
     * 
     * @type {number}
     * @memberof BooksPageResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof BooksPageResponse
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof BooksPageResponse
     */
    limit: number;
    /**
     * 
     * @type {Date}
     * @memberof BooksPageResponse
     */
    ratingLastSyncedOnUtc: Date | null;
}

/**
 * Check if a given object implements the BooksPageResponse interface.
 */
export function instanceOfBooksPageResponse(value: object): value is BooksPageResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('ratingLastSyncedOnUtc' in value) || value['ratingLastSyncedOnUtc'] === undefined) return false;
    return true;
}

export function BooksPageResponseFromJSON(json: any): BooksPageResponse {
    return BooksPageResponseFromJSONTyped(json, false);
}

export function BooksPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BookResponseFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
        'ratingLastSyncedOnUtc': (json['ratingLastSyncedOnUtc'] == null ? null : new Date(json['ratingLastSyncedOnUtc'])),
    };
}

export function BooksPageResponseToJSON(json: any): BooksPageResponse {
    return BooksPageResponseToJSONTyped(json, false);
}

export function BooksPageResponseToJSONTyped(value?: BooksPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BookResponseToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
        'ratingLastSyncedOnUtc': (value['ratingLastSyncedOnUtc'] == null ? null : (value['ratingLastSyncedOnUtc'] as any).toISOString()),
    };
}

