/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookCommentUserResponse
 */
export interface BookCommentUserResponse {
    /**
     * 
     * @type {string}
     * @memberof BookCommentUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookCommentUserResponse
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof BookCommentUserResponse
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof BookCommentUserResponse
     */
    avatarUrl: string | null;
}

/**
 * Check if a given object implements the BookCommentUserResponse interface.
 */
export function instanceOfBookCommentUserResponse(value: object): value is BookCommentUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    return true;
}

export function BookCommentUserResponseFromJSON(json: any): BookCommentUserResponse {
    return BookCommentUserResponseFromJSONTyped(json, false);
}

export function BookCommentUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookCommentUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['displayName'],
        'userName': json['userName'],
        'avatarUrl': json['avatarUrl'],
    };
}

export function BookCommentUserResponseToJSON(json: any): BookCommentUserResponse {
    return BookCommentUserResponseToJSONTyped(json, false);
}

export function BookCommentUserResponseToJSONTyped(value?: BookCommentUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'userName': value['userName'],
        'avatarUrl': value['avatarUrl'],
    };
}

