/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookCommentUserResponse } from './BookCommentUserResponse';
import {
    BookCommentUserResponseFromJSON,
    BookCommentUserResponseFromJSONTyped,
    BookCommentUserResponseToJSON,
    BookCommentUserResponseToJSONTyped,
} from './BookCommentUserResponse';

/**
 * 
 * @export
 * @interface BookCommentResponse
 */
export interface BookCommentResponse {
    /**
     * 
     * @type {string}
     * @memberof BookCommentResponse
     */
    id: string;
    /**
     * 
     * @type {BookCommentUserResponse}
     * @memberof BookCommentResponse
     */
    user: BookCommentUserResponse;
    /**
     * 
     * @type {string}
     * @memberof BookCommentResponse
     */
    body: string;
    /**
     * 
     * @type {Date}
     * @memberof BookCommentResponse
     */
    createdAtUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookCommentResponse
     */
    updatedAtUtc: Date | null;
}

/**
 * Check if a given object implements the BookCommentResponse interface.
 */
export function instanceOfBookCommentResponse(value: object): value is BookCommentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('createdAtUtc' in value) || value['createdAtUtc'] === undefined) return false;
    if (!('updatedAtUtc' in value) || value['updatedAtUtc'] === undefined) return false;
    return true;
}

export function BookCommentResponseFromJSON(json: any): BookCommentResponse {
    return BookCommentResponseFromJSONTyped(json, false);
}

export function BookCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': BookCommentUserResponseFromJSON(json['user']),
        'body': json['body'],
        'createdAtUtc': (new Date(json['createdAtUtc'])),
        'updatedAtUtc': (json['updatedAtUtc'] == null ? null : new Date(json['updatedAtUtc'])),
    };
}

export function BookCommentResponseToJSON(json: any): BookCommentResponse {
    return BookCommentResponseToJSONTyped(json, false);
}

export function BookCommentResponseToJSONTyped(value?: BookCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': BookCommentUserResponseToJSON(value['user']),
        'body': value['body'],
        'createdAtUtc': ((value['createdAtUtc']).toISOString()),
        'updatedAtUtc': (value['updatedAtUtc'] == null ? null : (value['updatedAtUtc'] as any).toISOString()),
    };
}

