/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookAuthorResponse } from './BookAuthorResponse';
import {
    BookAuthorResponseFromJSON,
    BookAuthorResponseFromJSONTyped,
    BookAuthorResponseToJSON,
    BookAuthorResponseToJSONTyped,
} from './BookAuthorResponse';
import type { BookSeriesInfo } from './BookSeriesInfo';
import {
    BookSeriesInfoFromJSON,
    BookSeriesInfoFromJSONTyped,
    BookSeriesInfoToJSON,
    BookSeriesInfoToJSONTyped,
} from './BookSeriesInfo';
import type { BookGenreResponse } from './BookGenreResponse';
import {
    BookGenreResponseFromJSON,
    BookGenreResponseFromJSONTyped,
    BookGenreResponseToJSON,
    BookGenreResponseToJSONTyped,
} from './BookGenreResponse';
import type { ApiAdminBooksPostRequestRating } from './ApiAdminBooksPostRequestRating';
import {
    ApiAdminBooksPostRequestRatingFromJSON,
    ApiAdminBooksPostRequestRatingFromJSONTyped,
    ApiAdminBooksPostRequestRatingToJSON,
    ApiAdminBooksPostRequestRatingToJSONTyped,
} from './ApiAdminBooksPostRequestRating';

/**
 * 
 * @export
 * @interface BookDetailResponse
 */
export interface BookDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    title: string;
    /**
     * 
     * @type {BookAuthorResponse}
     * @memberof BookDetailResponse
     */
    author: BookAuthorResponse;
    /**
     * 
     * @type {BookSeriesInfo}
     * @memberof BookDetailResponse
     */
    series: BookSeriesInfo | null;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    coverUrl: string;
    /**
     * 
     * @type {ApiAdminBooksPostRequestRating}
     * @memberof BookDetailResponse
     */
    rating: ApiAdminBooksPostRequestRating;
    /**
     * 
     * @type {number}
     * @memberof BookDetailResponse
     */
    ratingCount: number;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    ratingSource: string;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    sourceWorkId: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    sourceUrl: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BookDetailResponse
     */
    ratingSyncedOnUtc: Date | null;
    /**
     * 
     * @type {BookGenreResponse}
     * @memberof BookDetailResponse
     */
    genre: BookGenreResponse;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    status: string | null;
    /**
     * 
     * @type {number}
     * @memberof BookDetailResponse
     */
    commentsCount: number;
    /**
     * 
     * @type {string}
     * @memberof BookDetailResponse
     */
    titleEn: string | null;
}

/**
 * Check if a given object implements the BookDetailResponse interface.
 */
export function instanceOfBookDetailResponse(value: object): value is BookDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('series' in value) || value['series'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('ratingCount' in value) || value['ratingCount'] === undefined) return false;
    if (!('ratingSource' in value) || value['ratingSource'] === undefined) return false;
    if (!('sourceWorkId' in value) || value['sourceWorkId'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    if (!('ratingSyncedOnUtc' in value) || value['ratingSyncedOnUtc'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('commentsCount' in value) || value['commentsCount'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    return true;
}

export function BookDetailResponseFromJSON(json: any): BookDetailResponse {
    return BookDetailResponseFromJSONTyped(json, false);
}

export function BookDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'author': BookAuthorResponseFromJSON(json['author']),
        'series': BookSeriesInfoFromJSON(json['series']),
        'coverUrl': json['coverUrl'],
        'rating': ApiAdminBooksPostRequestRatingFromJSON(json['rating']),
        'ratingCount': json['ratingCount'],
        'ratingSource': json['ratingSource'],
        'sourceWorkId': json['sourceWorkId'],
        'sourceUrl': json['sourceUrl'],
        'ratingSyncedOnUtc': (json['ratingSyncedOnUtc'] == null ? null : new Date(json['ratingSyncedOnUtc'])),
        'genre': BookGenreResponseFromJSON(json['genre']),
        'status': json['status'],
        'commentsCount': json['commentsCount'],
        'titleEn': json['titleEn'],
    };
}

export function BookDetailResponseToJSON(json: any): BookDetailResponse {
    return BookDetailResponseToJSONTyped(json, false);
}

export function BookDetailResponseToJSONTyped(value?: BookDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'author': BookAuthorResponseToJSON(value['author']),
        'series': BookSeriesInfoToJSON(value['series']),
        'coverUrl': value['coverUrl'],
        'rating': ApiAdminBooksPostRequestRatingToJSON(value['rating']),
        'ratingCount': value['ratingCount'],
        'ratingSource': value['ratingSource'],
        'sourceWorkId': value['sourceWorkId'],
        'sourceUrl': value['sourceUrl'],
        'ratingSyncedOnUtc': (value['ratingSyncedOnUtc'] == null ? null : (value['ratingSyncedOnUtc'] as any).toISOString()),
        'genre': BookGenreResponseToJSON(value['genre']),
        'status': value['status'],
        'commentsCount': value['commentsCount'],
        'titleEn': value['titleEn'],
    };
}

