/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreResponse
 */
export interface GenreResponse {
    /**
     * 
     * @type {string}
     * @memberof GenreResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GenreResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof GenreResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GenreResponse
     */
    sortOrder: number;
    /**
     * 
     * @type {number}
     * @memberof GenreResponse
     */
    bookCount: number;
}

/**
 * Check if a given object implements the GenreResponse interface.
 */
export function instanceOfGenreResponse(value: object): value is GenreResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('bookCount' in value) || value['bookCount'] === undefined) return false;
    return true;
}

export function GenreResponseFromJSON(json: any): GenreResponse {
    return GenreResponseFromJSONTyped(json, false);
}

export function GenreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'sortOrder': json['sortOrder'],
        'bookCount': json['bookCount'],
    };
}

export function GenreResponseToJSON(json: any): GenreResponse {
    return GenreResponseToJSONTyped(json, false);
}

export function GenreResponseToJSONTyped(value?: GenreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'sortOrder': value['sortOrder'],
        'bookCount': value['bookCount'],
    };
}

