/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatingImportItemRequest } from './RatingImportItemRequest';
import {
    RatingImportItemRequestFromJSON,
    RatingImportItemRequestFromJSONTyped,
    RatingImportItemRequestToJSON,
    RatingImportItemRequestToJSONTyped,
} from './RatingImportItemRequest';

/**
 * 
 * @export
 * @interface ImportBookRatingsRequest
 */
export interface ImportBookRatingsRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportBookRatingsRequest
     */
    source: string;
    /**
     * 
     * @type {Array<RatingImportItemRequest>}
     * @memberof ImportBookRatingsRequest
     */
    items: Array<RatingImportItemRequest>;
}

/**
 * Check if a given object implements the ImportBookRatingsRequest interface.
 */
export function instanceOfImportBookRatingsRequest(value: object): value is ImportBookRatingsRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ImportBookRatingsRequestFromJSON(json: any): ImportBookRatingsRequest {
    return ImportBookRatingsRequestFromJSONTyped(json, false);
}

export function ImportBookRatingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportBookRatingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'items': ((json['items'] as Array<any>).map(RatingImportItemRequestFromJSON)),
    };
}

export function ImportBookRatingsRequestToJSON(json: any): ImportBookRatingsRequest {
    return ImportBookRatingsRequestToJSONTyped(json, false);
}

export function ImportBookRatingsRequestToJSONTyped(value?: ImportBookRatingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'items': ((value['items'] as Array<any>).map(RatingImportItemRequestToJSON)),
    };
}

