/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaderboardEntryResponse } from './LeaderboardEntryResponse';
import {
    LeaderboardEntryResponseFromJSON,
    LeaderboardEntryResponseFromJSONTyped,
    LeaderboardEntryResponseToJSON,
    LeaderboardEntryResponseToJSONTyped,
} from './LeaderboardEntryResponse';

/**
 * 
 * @export
 * @interface LeaderboardResponse
 */
export interface LeaderboardResponse {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardResponse
     */
    game: string;
    /**
     * 
     * @type {Array<LeaderboardEntryResponse>}
     * @memberof LeaderboardResponse
     */
    entries: Array<LeaderboardEntryResponse>;
}

/**
 * Check if a given object implements the LeaderboardResponse interface.
 */
export function instanceOfLeaderboardResponse(value: object): value is LeaderboardResponse {
    if (!('game' in value) || value['game'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function LeaderboardResponseFromJSON(json: any): LeaderboardResponse {
    return LeaderboardResponseFromJSONTyped(json, false);
}

export function LeaderboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'game': json['game'],
        'entries': ((json['entries'] as Array<any>).map(LeaderboardEntryResponseFromJSON)),
    };
}

export function LeaderboardResponseToJSON(json: any): LeaderboardResponse {
    return LeaderboardResponseToJSONTyped(json, false);
}

export function LeaderboardResponseToJSONTyped(value?: LeaderboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game': value['game'],
        'entries': ((value['entries'] as Array<any>).map(LeaderboardEntryResponseToJSON)),
    };
}

