/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManageSeriesRequest
 */
export interface ManageSeriesRequest {
    /**
     * 
     * @type {string}
     * @memberof ManageSeriesRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ManageSeriesRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ManageSeriesRequest
     */
    titleEn: string;
}

/**
 * Check if a given object implements the ManageSeriesRequest interface.
 */
export function instanceOfManageSeriesRequest(value: object): value is ManageSeriesRequest {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    return true;
}

export function ManageSeriesRequestFromJSON(json: any): ManageSeriesRequest {
    return ManageSeriesRequestFromJSONTyped(json, false);
}

export function ManageSeriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageSeriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'title': json['title'],
        'titleEn': json['titleEn'],
    };
}

export function ManageSeriesRequestToJSON(json: any): ManageSeriesRequest {
    return ManageSeriesRequestToJSONTyped(json, false);
}

export function ManageSeriesRequestToJSONTyped(value?: ManageSeriesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'title': value['title'],
        'titleEn': value['titleEn'],
    };
}

