/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface MostActiveUserResponse
 */
export interface MostActiveUserResponse {
    /**
     * 
     * @type {UserResponse}
     * @memberof MostActiveUserResponse
     */
    user: UserResponse;
    /**
     * 
     * @type {number}
     * @memberof MostActiveUserResponse
     */
    postCount: number;
    /**
     * 
     * @type {number}
     * @memberof MostActiveUserResponse
     */
    netRating: number;
}

/**
 * Check if a given object implements the MostActiveUserResponse interface.
 */
export function instanceOfMostActiveUserResponse(value: object): value is MostActiveUserResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('postCount' in value) || value['postCount'] === undefined) return false;
    if (!('netRating' in value) || value['netRating'] === undefined) return false;
    return true;
}

export function MostActiveUserResponseFromJSON(json: any): MostActiveUserResponse {
    return MostActiveUserResponseFromJSONTyped(json, false);
}

export function MostActiveUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MostActiveUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserResponseFromJSON(json['user']),
        'postCount': json['postCount'],
        'netRating': json['netRating'],
    };
}

export function MostActiveUserResponseToJSON(json: any): MostActiveUserResponse {
    return MostActiveUserResponseToJSONTyped(json, false);
}

export function MostActiveUserResponseToJSONTyped(value?: MostActiveUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserResponseToJSON(value['user']),
        'postCount': value['postCount'],
        'netRating': value['netRating'],
    };
}

