/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostRatingHistoryPoint } from './PostRatingHistoryPoint';
import {
    PostRatingHistoryPointFromJSON,
    PostRatingHistoryPointFromJSONTyped,
    PostRatingHistoryPointToJSON,
    PostRatingHistoryPointToJSONTyped,
} from './PostRatingHistoryPoint';

/**
 * 
 * @export
 * @interface PostRatingHistoryResponse
 */
export interface PostRatingHistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof PostRatingHistoryResponse
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof PostRatingHistoryResponse
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof PostRatingHistoryResponse
     */
    rating: number;
    /**
     * 
     * @type {number}
     * @memberof PostRatingHistoryResponse
     */
    upVotes: number;
    /**
     * 
     * @type {number}
     * @memberof PostRatingHistoryResponse
     */
    downVotes: number;
    /**
     * 
     * @type {Array<PostRatingHistoryPoint>}
     * @memberof PostRatingHistoryResponse
     */
    series: Array<PostRatingHistoryPoint>;
}

/**
 * Check if a given object implements the PostRatingHistoryResponse interface.
 */
export function instanceOfPostRatingHistoryResponse(value: object): value is PostRatingHistoryResponse {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('upVotes' in value) || value['upVotes'] === undefined) return false;
    if (!('downVotes' in value) || value['downVotes'] === undefined) return false;
    if (!('series' in value) || value['series'] === undefined) return false;
    return true;
}

export function PostRatingHistoryResponseFromJSON(json: any): PostRatingHistoryResponse {
    return PostRatingHistoryResponseFromJSONTyped(json, false);
}

export function PostRatingHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRatingHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'slug': json['slug'],
        'rating': json['rating'],
        'upVotes': json['upVotes'],
        'downVotes': json['downVotes'],
        'series': ((json['series'] as Array<any>).map(PostRatingHistoryPointFromJSON)),
    };
}

export function PostRatingHistoryResponseToJSON(json: any): PostRatingHistoryResponse {
    return PostRatingHistoryResponseToJSONTyped(json, false);
}

export function PostRatingHistoryResponseToJSONTyped(value?: PostRatingHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'slug': value['slug'],
        'rating': value['rating'],
        'upVotes': value['upVotes'],
        'downVotes': value['downVotes'],
        'series': ((value['series'] as Array<any>).map(PostRatingHistoryPointToJSON)),
    };
}

