/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreatedResponse
 */
export interface PostCreatedResponse {
    /**
     * 
     * @type {string}
     * @memberof PostCreatedResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreatedResponse
     */
    slug: string;
}

/**
 * Check if a given object implements the PostCreatedResponse interface.
 */
export function instanceOfPostCreatedResponse(value: object): value is PostCreatedResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PostCreatedResponseFromJSON(json: any): PostCreatedResponse {
    return PostCreatedResponseFromJSONTyped(json, false);
}

export function PostCreatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
    };
}

export function PostCreatedResponseToJSON(json: any): PostCreatedResponse {
    return PostCreatedResponseToJSONTyped(json, false);
}

export function PostCreatedResponseToJSONTyped(value?: PostCreatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
    };
}

