/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostRatingHistoryPoint
 */
export interface PostRatingHistoryPoint {
    /**
     * 
     * @type {Date}
     * @memberof PostRatingHistoryPoint
     */
    timestampUtc: Date;
    /**
     * 
     * @type {number}
     * @memberof PostRatingHistoryPoint
     */
    cumulativeRating: number;
}

/**
 * Check if a given object implements the PostRatingHistoryPoint interface.
 */
export function instanceOfPostRatingHistoryPoint(value: object): value is PostRatingHistoryPoint {
    if (!('timestampUtc' in value) || value['timestampUtc'] === undefined) return false;
    if (!('cumulativeRating' in value) || value['cumulativeRating'] === undefined) return false;
    return true;
}

export function PostRatingHistoryPointFromJSON(json: any): PostRatingHistoryPoint {
    return PostRatingHistoryPointFromJSONTyped(json, false);
}

export function PostRatingHistoryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRatingHistoryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'timestampUtc': (new Date(json['timestampUtc'])),
        'cumulativeRating': json['cumulativeRating'],
    };
}

export function PostRatingHistoryPointToJSON(json: any): PostRatingHistoryPoint {
    return PostRatingHistoryPointToJSONTyped(json, false);
}

export function PostRatingHistoryPointToJSONTyped(value?: PostRatingHistoryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestampUtc': ((value['timestampUtc']).toISOString()),
        'cumulativeRating': value['cumulativeRating'],
    };
}

