/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSyncResponse
 */
export interface RatingSyncResponse {
    /**
     * 
     * @type {string}
     * @memberof RatingSyncResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSyncResponse
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof RatingSyncResponse
     */
    booksSeen: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSyncResponse
     */
    booksUpdated: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSyncResponse
     */
    booksFailed: number;
    /**
     * 
     * @type {Date}
     * @memberof RatingSyncResponse
     */
    completedOnUtc: Date;
}

/**
 * Check if a given object implements the RatingSyncResponse interface.
 */
export function instanceOfRatingSyncResponse(value: object): value is RatingSyncResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('booksSeen' in value) || value['booksSeen'] === undefined) return false;
    if (!('booksUpdated' in value) || value['booksUpdated'] === undefined) return false;
    if (!('booksFailed' in value) || value['booksFailed'] === undefined) return false;
    if (!('completedOnUtc' in value) || value['completedOnUtc'] === undefined) return false;
    return true;
}

export function RatingSyncResponseFromJSON(json: any): RatingSyncResponse {
    return RatingSyncResponseFromJSONTyped(json, false);
}

export function RatingSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSyncResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'source': json['source'],
        'booksSeen': json['booksSeen'],
        'booksUpdated': json['booksUpdated'],
        'booksFailed': json['booksFailed'],
        'completedOnUtc': (new Date(json['completedOnUtc'])),
    };
}

export function RatingSyncResponseToJSON(json: any): RatingSyncResponse {
    return RatingSyncResponseToJSONTyped(json, false);
}

export function RatingSyncResponseToJSONTyped(value?: RatingSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'source': value['source'],
        'booksSeen': value['booksSeen'],
        'booksUpdated': value['booksUpdated'],
        'booksFailed': value['booksFailed'],
        'completedOnUtc': ((value['completedOnUtc']).toISOString()),
    };
}

