/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAdminBooksPostRequestRating } from './ApiAdminBooksPostRequestRating';
import {
    ApiAdminBooksPostRequestRatingFromJSON,
    ApiAdminBooksPostRequestRatingFromJSONTyped,
    ApiAdminBooksPostRequestRatingToJSON,
    ApiAdminBooksPostRequestRatingToJSONTyped,
} from './ApiAdminBooksPostRequestRating';

/**
 * 
 * @export
 * @interface RatingImportItemRequest
 */
export interface RatingImportItemRequest {
    /**
     * 
     * @type {string}
     * @memberof RatingImportItemRequest
     */
    sourceWorkId: string;
    /**
     * 
     * @type {ApiAdminBooksPostRequestRating}
     * @memberof RatingImportItemRequest
     */
    rating: ApiAdminBooksPostRequestRating;
    /**
     * 
     * @type {number}
     * @memberof RatingImportItemRequest
     */
    ratingCount: number;
}

/**
 * Check if a given object implements the RatingImportItemRequest interface.
 */
export function instanceOfRatingImportItemRequest(value: object): value is RatingImportItemRequest {
    if (!('sourceWorkId' in value) || value['sourceWorkId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('ratingCount' in value) || value['ratingCount'] === undefined) return false;
    return true;
}

export function RatingImportItemRequestFromJSON(json: any): RatingImportItemRequest {
    return RatingImportItemRequestFromJSONTyped(json, false);
}

export function RatingImportItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingImportItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceWorkId': json['sourceWorkId'],
        'rating': ApiAdminBooksPostRequestRatingFromJSON(json['rating']),
        'ratingCount': json['ratingCount'],
    };
}

export function RatingImportItemRequestToJSON(json: any): RatingImportItemRequest {
    return RatingImportItemRequestToJSONTyped(json, false);
}

export function RatingImportItemRequestToJSONTyped(value?: RatingImportItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceWorkId': value['sourceWorkId'],
        'rating': ApiAdminBooksPostRequestRatingToJSON(value['rating']),
        'ratingCount': value['ratingCount'],
    };
}

