/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeriesResponse
 */
export interface SeriesResponse {
    /**
     * 
     * @type {string}
     * @memberof SeriesResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesResponse
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof SeriesResponse
     */
    bookCount: number;
    /**
     * 
     * @type {string}
     * @memberof SeriesResponse
     */
    titleEn: string | null;
}

/**
 * Check if a given object implements the SeriesResponse interface.
 */
export function instanceOfSeriesResponse(value: object): value is SeriesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('bookCount' in value) || value['bookCount'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    return true;
}

export function SeriesResponseFromJSON(json: any): SeriesResponse {
    return SeriesResponseFromJSONTyped(json, false);
}

export function SeriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'bookCount': json['bookCount'],
        'titleEn': json['titleEn'],
    };
}

export function SeriesResponseToJSON(json: any): SeriesResponse {
    return SeriesResponseToJSONTyped(json, false);
}

export function SeriesResponseToJSONTyped(value?: SeriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'bookCount': value['bookCount'],
        'titleEn': value['titleEn'],
    };
}

