/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookResponse } from './BookResponse';
import {
    BookResponseFromJSON,
    BookResponseFromJSONTyped,
    BookResponseToJSON,
    BookResponseToJSONTyped,
} from './BookResponse';

/**
 * 
 * @export
 * @interface SeriesDetailResponse
 */
export interface SeriesDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailResponse
     */
    title: string;
    /**
     * 
     * @type {Array<BookResponse>}
     * @memberof SeriesDetailResponse
     */
    volumes: Array<BookResponse>;
    /**
     * 
     * @type {string}
     * @memberof SeriesDetailResponse
     */
    titleEn: string | null;
}

/**
 * Check if a given object implements the SeriesDetailResponse interface.
 */
export function instanceOfSeriesDetailResponse(value: object): value is SeriesDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('volumes' in value) || value['volumes'] === undefined) return false;
    if (!('titleEn' in value) || value['titleEn'] === undefined) return false;
    return true;
}

export function SeriesDetailResponseFromJSON(json: any): SeriesDetailResponse {
    return SeriesDetailResponseFromJSONTyped(json, false);
}

export function SeriesDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'volumes': ((json['volumes'] as Array<any>).map(BookResponseFromJSON)),
        'titleEn': json['titleEn'],
    };
}

export function SeriesDetailResponseToJSON(json: any): SeriesDetailResponse {
    return SeriesDetailResponseToJSONTyped(json, false);
}

export function SeriesDetailResponseToJSONTyped(value?: SeriesDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'volumes': ((value['volumes'] as Array<any>).map(BookResponseToJSON)),
        'titleEn': value['titleEn'],
    };
}

