/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetBookStatusRequest
 */
export interface SetBookStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof SetBookStatusRequest
     */
    status: string;
}

/**
 * Check if a given object implements the SetBookStatusRequest interface.
 */
export function instanceOfSetBookStatusRequest(value: object): value is SetBookStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SetBookStatusRequestFromJSON(json: any): SetBookStatusRequest {
    return SetBookStatusRequestFromJSONTyped(json, false);
}

export function SetBookStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetBookStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function SetBookStatusRequestToJSON(json: any): SetBookStatusRequest {
    return SetBookStatusRequestToJSONTyped(json, false);
}

export function SetBookStatusRequestToJSONTyped(value?: SetBookStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

