/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookAuthorResponse } from './BookAuthorResponse';
import {
    BookAuthorResponseFromJSON,
    BookAuthorResponseFromJSONTyped,
    BookAuthorResponseToJSON,
    BookAuthorResponseToJSONTyped,
} from './BookAuthorResponse';
import type { BookGenreResponse } from './BookGenreResponse';
import {
    BookGenreResponseFromJSON,
    BookGenreResponseFromJSONTyped,
    BookGenreResponseToJSON,
    BookGenreResponseToJSONTyped,
} from './BookGenreResponse';
import type { ShelfBookCardRatingCount } from './ShelfBookCardRatingCount';
import {
    ShelfBookCardRatingCountFromJSON,
    ShelfBookCardRatingCountFromJSONTyped,
    ShelfBookCardRatingCountToJSON,
    ShelfBookCardRatingCountToJSONTyped,
} from './ShelfBookCardRatingCount';
import type { ApiAdminBooksPostRequestRating } from './ApiAdminBooksPostRequestRating';
import {
    ApiAdminBooksPostRequestRatingFromJSON,
    ApiAdminBooksPostRequestRatingFromJSONTyped,
    ApiAdminBooksPostRequestRatingToJSON,
    ApiAdminBooksPostRequestRatingToJSONTyped,
} from './ApiAdminBooksPostRequestRating';

/**
 * 
 * @export
 * @interface ShelfBookCard
 */
export interface ShelfBookCard {
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    type?: ShelfBookCardTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    title: string;
    /**
     * 
     * @type {BookAuthorResponse}
     * @memberof ShelfBookCard
     */
    author: BookAuthorResponse;
    /**
     * 
     * @type {BookGenreResponse}
     * @memberof ShelfBookCard
     */
    genre: BookGenreResponse;
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    coverUrl: string;
    /**
     * 
     * @type {ApiAdminBooksPostRequestRating}
     * @memberof ShelfBookCard
     */
    rating: ApiAdminBooksPostRequestRating;
    /**
     * 
     * @type {ShelfBookCardRatingCount}
     * @memberof ShelfBookCard
     */
    ratingCount: ShelfBookCardRatingCount;
    /**
     * 
     * @type {string}
     * @memberof ShelfBookCard
     */
    status: string | null;
}


/**
 * @export
 */
export const ShelfBookCardTypeEnum = {
    Book: 'book'
} as const;
export type ShelfBookCardTypeEnum = typeof ShelfBookCardTypeEnum[keyof typeof ShelfBookCardTypeEnum];


/**
 * Check if a given object implements the ShelfBookCard interface.
 */
export function instanceOfShelfBookCard(value: object): value is ShelfBookCard {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('ratingCount' in value) || value['ratingCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ShelfBookCardFromJSON(json: any): ShelfBookCard {
    return ShelfBookCardFromJSONTyped(json, false);
}

export function ShelfBookCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfBookCard {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'],
        'slug': json['slug'],
        'title': json['title'],
        'author': BookAuthorResponseFromJSON(json['author']),
        'genre': BookGenreResponseFromJSON(json['genre']),
        'coverUrl': json['coverUrl'],
        'rating': ApiAdminBooksPostRequestRatingFromJSON(json['rating']),
        'ratingCount': ShelfBookCardRatingCountFromJSON(json['ratingCount']),
        'status': json['status'],
    };
}

export function ShelfBookCardToJSON(json: any): ShelfBookCard {
    return ShelfBookCardToJSONTyped(json, false);
}

export function ShelfBookCardToJSONTyped(value?: ShelfBookCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'slug': value['slug'],
        'title': value['title'],
        'author': BookAuthorResponseToJSON(value['author']),
        'genre': BookGenreResponseToJSON(value['genre']),
        'coverUrl': value['coverUrl'],
        'rating': ApiAdminBooksPostRequestRatingToJSON(value['rating']),
        'ratingCount': ShelfBookCardRatingCountToJSON(value['ratingCount']),
        'status': value['status'],
    };
}

