/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShelfBookCardRatingCount
 */
export interface ShelfBookCardRatingCount {
}

/**
 * Check if a given object implements the ShelfBookCardRatingCount interface.
 */
export function instanceOfShelfBookCardRatingCount(value: object): value is ShelfBookCardRatingCount {
    return true;
}

export function ShelfBookCardRatingCountFromJSON(json: any): ShelfBookCardRatingCount {
    return ShelfBookCardRatingCountFromJSONTyped(json, false);
}

export function ShelfBookCardRatingCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfBookCardRatingCount {
    return json;
}

export function ShelfBookCardRatingCountToJSON(json: any): ShelfBookCardRatingCount {
    return ShelfBookCardRatingCountToJSONTyped(json, false);
}

export function ShelfBookCardRatingCountToJSONTyped(value?: ShelfBookCardRatingCount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

