/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ShelfBookCard } from './ShelfBookCard';
import {
    instanceOfShelfBookCard,
    ShelfBookCardFromJSON,
    ShelfBookCardFromJSONTyped,
    ShelfBookCardToJSON,
} from './ShelfBookCard';
import type { ShelfSeriesCard } from './ShelfSeriesCard';
import {
    instanceOfShelfSeriesCard,
    ShelfSeriesCardFromJSON,
    ShelfSeriesCardFromJSONTyped,
    ShelfSeriesCardToJSON,
} from './ShelfSeriesCard';

/**
 * @type ShelfCatalogItem
 * 
 * @export
 */
export type ShelfCatalogItem = { type: 'book' } & ShelfBookCard | { type: 'series' } & ShelfSeriesCard;

export function ShelfCatalogItemFromJSON(json: any): ShelfCatalogItem {
    return ShelfCatalogItemFromJSONTyped(json, false);
}

export function ShelfCatalogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfCatalogItem {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'book':
            return Object.assign({}, ShelfBookCardFromJSONTyped(json, true), { type: 'book' } as const);
        case 'series':
            return Object.assign({}, ShelfSeriesCardFromJSONTyped(json, true), { type: 'series' } as const);
        default:
            throw new Error(`No variant of ShelfCatalogItem exists with 'type=${json['type']}'`);
    }
}

export function ShelfCatalogItemToJSON(json: any): any {
    return ShelfCatalogItemToJSONTyped(json, false);
}

export function ShelfCatalogItemToJSONTyped(value?: ShelfCatalogItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'book':
            return Object.assign({}, ShelfBookCardToJSON(value), { type: 'book' } as const);
        case 'series':
            return Object.assign({}, ShelfSeriesCardToJSON(value), { type: 'series' } as const);
        default:
            throw new Error(`No variant of ShelfCatalogItem exists with 'type=${value['type']}'`);
    }

}

