/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShelfCatalogItem } from './ShelfCatalogItem';
import {
    ShelfCatalogItemFromJSON,
    ShelfCatalogItemFromJSONTyped,
    ShelfCatalogItemToJSON,
    ShelfCatalogItemToJSONTyped,
} from './ShelfCatalogItem';

/**
 * 
 * @export
 * @interface ShelfCatalogResponse
 */
export interface ShelfCatalogResponse {
    /**
     * 
     * @type {Array<ShelfCatalogItem>}
     * @memberof ShelfCatalogResponse
     */
    items: Array<ShelfCatalogItem>;
    /**
     * 
     * @type {number}
     * @memberof ShelfCatalogResponse
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof ShelfCatalogResponse
     */
    totalBooks: number;
    /**
     * 
     * @type {number}
     * @memberof ShelfCatalogResponse
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof ShelfCatalogResponse
     */
    limit: number;
    /**
     * 
     * @type {Date}
     * @memberof ShelfCatalogResponse
     */
    ratingLastSyncedOnUtc: Date | null;
}

/**
 * Check if a given object implements the ShelfCatalogResponse interface.
 */
export function instanceOfShelfCatalogResponse(value: object): value is ShelfCatalogResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalBooks' in value) || value['totalBooks'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('ratingLastSyncedOnUtc' in value) || value['ratingLastSyncedOnUtc'] === undefined) return false;
    return true;
}

export function ShelfCatalogResponseFromJSON(json: any): ShelfCatalogResponse {
    return ShelfCatalogResponseFromJSONTyped(json, false);
}

export function ShelfCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ShelfCatalogItemFromJSON)),
        'totalItems': json['totalItems'],
        'totalBooks': json['totalBooks'],
        'offset': json['offset'],
        'limit': json['limit'],
        'ratingLastSyncedOnUtc': (json['ratingLastSyncedOnUtc'] == null ? null : new Date(json['ratingLastSyncedOnUtc'])),
    };
}

export function ShelfCatalogResponseToJSON(json: any): ShelfCatalogResponse {
    return ShelfCatalogResponseToJSONTyped(json, false);
}

export function ShelfCatalogResponseToJSONTyped(value?: ShelfCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ShelfCatalogItemToJSON)),
        'totalItems': value['totalItems'],
        'totalBooks': value['totalBooks'],
        'offset': value['offset'],
        'limit': value['limit'],
        'ratingLastSyncedOnUtc': (value['ratingLastSyncedOnUtc'] == null ? null : (value['ratingLastSyncedOnUtc'] as any).toISOString()),
    };
}

