/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitScoreRequest
 */
export interface SubmitScoreRequest {
    /**
     * 
     * @type {number}
     * @memberof SubmitScoreRequest
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof SubmitScoreRequest
     */
    game?: string | null;
}

/**
 * Check if a given object implements the SubmitScoreRequest interface.
 */
export function instanceOfSubmitScoreRequest(value: object): value is SubmitScoreRequest {
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function SubmitScoreRequestFromJSON(json: any): SubmitScoreRequest {
    return SubmitScoreRequestFromJSONTyped(json, false);
}

export function SubmitScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitScoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
        'game': json['game'] == null ? undefined : json['game'],
    };
}

export function SubmitScoreRequestToJSON(json: any): SubmitScoreRequest {
    return SubmitScoreRequestToJSONTyped(json, false);
}

export function SubmitScoreRequestToJSONTyped(value?: SubmitScoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'game': value['game'],
    };
}

