/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopPostResponse
 */
export interface TopPostResponse {
    /**
     * 
     * @type {string}
     * @memberof TopPostResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TopPostResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TopPostResponse
     */
    userName: string;
    /**
     * 
     * @type {number}
     * @memberof TopPostResponse
     */
    views: number;
    /**
     * 
     * @type {number}
     * @memberof TopPostResponse
     */
    netRating: number;
}

/**
 * Check if a given object implements the TopPostResponse interface.
 */
export function instanceOfTopPostResponse(value: object): value is TopPostResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('views' in value) || value['views'] === undefined) return false;
    if (!('netRating' in value) || value['netRating'] === undefined) return false;
    return true;
}

export function TopPostResponseFromJSON(json: any): TopPostResponse {
    return TopPostResponseFromJSONTyped(json, false);
}

export function TopPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'slug': json['slug'],
        'userName': json['userName'],
        'views': json['views'],
        'netRating': json['netRating'],
    };
}

export function TopPostResponseToJSON(json: any): TopPostResponse {
    return TopPostResponseToJSONTyped(json, false);
}

export function TopPostResponseToJSONTyped(value?: TopPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'userName': value['userName'],
        'views': value['views'],
        'netRating': value['netRating'],
    };
}

