/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePostRequest
 */
export interface UpdatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostRequest
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostRequest
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostRequest
     */
    coverUrl: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePostRequest
     */
    tags: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePostRequest
     */
    isPublished: boolean;
}

/**
 * Check if a given object implements the UpdatePostRequest interface.
 */
export function instanceOfUpdatePostRequest(value: object): value is UpdatePostRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('isPublished' in value) || value['isPublished'] === undefined) return false;
    return true;
}

export function UpdatePostRequestFromJSON(json: any): UpdatePostRequest {
    return UpdatePostRequestFromJSONTyped(json, false);
}

export function UpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'summary': json['summary'],
        'body': json['body'],
        'slug': json['slug'],
        'coverUrl': json['coverUrl'],
        'tags': json['tags'],
        'isPublished': json['isPublished'],
    };
}

export function UpdatePostRequestToJSON(json: any): UpdatePostRequest {
    return UpdatePostRequestToJSONTyped(json, false);
}

export function UpdatePostRequestToJSONTyped(value?: UpdatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'summary': value['summary'],
        'body': value['body'],
        'slug': value['slug'],
        'coverUrl': value['coverUrl'],
        'tags': value['tags'],
        'isPublished': value['isPublished'],
    };
}

