/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCommentResponse
 */
export interface UserCommentResponse {
    /**
     * 
     * @type {string}
     * @memberof UserCommentResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof UserCommentResponse
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentResponse
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentResponse
     */
    avatarUrl: string | null;
}

/**
 * Check if a given object implements the UserCommentResponse interface.
 */
export function instanceOfUserCommentResponse(value: object): value is UserCommentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    return true;
}

export function UserCommentResponseFromJSON(json: any): UserCommentResponse {
    return UserCommentResponseFromJSONTyped(json, false);
}

export function UserCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['displayName'],
        'userName': json['userName'],
        'avatarUrl': json['avatarUrl'],
    };
}

export function UserCommentResponseToJSON(json: any): UserCommentResponse {
    return UserCommentResponseToJSONTyped(json, false);
}

export function UserCommentResponseToJSONTyped(value?: UserCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'userName': value['userName'],
        'avatarUrl': value['avatarUrl'],
    };
}

