/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookAuthorResponse,
  IdResponse,
  ManageAuthorRequest,
  ProblemDetails,
} from '../models/index';
import {
    BookAuthorResponseFromJSON,
    BookAuthorResponseToJSON,
    IdResponseFromJSON,
    IdResponseToJSON,
    ManageAuthorRequestFromJSON,
    ManageAuthorRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiAdminAuthorsGetRequest {
    query?: string;
}

export interface ApiAdminAuthorsIdDeleteRequest {
    id: string;
}

export interface ApiAdminAuthorsIdPutRequest {
    id: string;
    manageAuthorRequest: ManageAuthorRequest;
}

export interface ApiAdminAuthorsPostRequest {
    manageAuthorRequest: ManageAuthorRequest;
}

/**
 * AdminAuthorsApi - interface
 * 
 * @export
 * @interface AdminAuthorsApiInterface
 */
export interface AdminAuthorsApiInterface {
    /**
     * 
     * @param {string} [query] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthorsApiInterface
     */
    apiAdminAuthorsGetRaw(requestParameters: ApiAdminAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookAuthorResponse>>>;

    /**
     */
    apiAdminAuthorsGet(requestParameters: ApiAdminAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookAuthorResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthorsApiInterface
     */
    apiAdminAuthorsIdDeleteRaw(requestParameters: ApiAdminAuthorsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminAuthorsIdDelete(requestParameters: ApiAdminAuthorsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {ManageAuthorRequest} manageAuthorRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthorsApiInterface
     */
    apiAdminAuthorsIdPutRaw(requestParameters: ApiAdminAuthorsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminAuthorsIdPut(requestParameters: ApiAdminAuthorsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {ManageAuthorRequest} manageAuthorRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthorsApiInterface
     */
    apiAdminAuthorsPostRaw(requestParameters: ApiAdminAuthorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     */
    apiAdminAuthorsPost(requestParameters: ApiAdminAuthorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse>;

}

/**
 * 
 */
export class AdminAuthorsApi extends runtime.BaseAPI implements AdminAuthorsApiInterface {

    /**
     */
    async apiAdminAuthorsGetRaw(requestParameters: ApiAdminAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookAuthorResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/authors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookAuthorResponseFromJSON));
    }

    /**
     */
    async apiAdminAuthorsGet(requestParameters: ApiAdminAuthorsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookAuthorResponse>> {
        const response = await this.apiAdminAuthorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminAuthorsIdDeleteRaw(requestParameters: ApiAdminAuthorsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminAuthorsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/authors/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminAuthorsIdDelete(requestParameters: ApiAdminAuthorsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminAuthorsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminAuthorsIdPutRaw(requestParameters: ApiAdminAuthorsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminAuthorsIdPut().'
            );
        }

        if (requestParameters['manageAuthorRequest'] == null) {
            throw new runtime.RequiredError(
                'manageAuthorRequest',
                'Required parameter "manageAuthorRequest" was null or undefined when calling apiAdminAuthorsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/authors/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ManageAuthorRequestToJSON(requestParameters['manageAuthorRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminAuthorsIdPut(requestParameters: ApiAdminAuthorsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminAuthorsIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminAuthorsPostRaw(requestParameters: ApiAdminAuthorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>> {
        if (requestParameters['manageAuthorRequest'] == null) {
            throw new runtime.RequiredError(
                'manageAuthorRequest',
                'Required parameter "manageAuthorRequest" was null or undefined when calling apiAdminAuthorsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/authors`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ManageAuthorRequestToJSON(requestParameters['manageAuthorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminAuthorsPost(requestParameters: ApiAdminAuthorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse> {
        const response = await this.apiAdminAuthorsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
