/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenreResponse,
  IdResponse,
  ManageGenreRequest,
  ProblemDetails,
} from '../models/index';
import {
    GenreResponseFromJSON,
    GenreResponseToJSON,
    IdResponseFromJSON,
    IdResponseToJSON,
    ManageGenreRequestFromJSON,
    ManageGenreRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiAdminGenresIdDeleteRequest {
    id: string;
}

export interface ApiAdminGenresIdPutRequest {
    id: string;
    manageGenreRequest: ManageGenreRequest;
}

export interface ApiAdminGenresPostRequest {
    manageGenreRequest: ManageGenreRequest;
}

/**
 * AdminGenresApi - interface
 * 
 * @export
 * @interface AdminGenresApiInterface
 */
export interface AdminGenresApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminGenresApiInterface
     */
    apiAdminGenresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GenreResponse>>>;

    /**
     */
    apiAdminGenresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GenreResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminGenresApiInterface
     */
    apiAdminGenresIdDeleteRaw(requestParameters: ApiAdminGenresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminGenresIdDelete(requestParameters: ApiAdminGenresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {ManageGenreRequest} manageGenreRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminGenresApiInterface
     */
    apiAdminGenresIdPutRaw(requestParameters: ApiAdminGenresIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminGenresIdPut(requestParameters: ApiAdminGenresIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {ManageGenreRequest} manageGenreRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminGenresApiInterface
     */
    apiAdminGenresPostRaw(requestParameters: ApiAdminGenresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     */
    apiAdminGenresPost(requestParameters: ApiAdminGenresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse>;

}

/**
 * 
 */
export class AdminGenresApi extends runtime.BaseAPI implements AdminGenresApiInterface {

    /**
     */
    async apiAdminGenresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GenreResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/genres`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreResponseFromJSON));
    }

    /**
     */
    async apiAdminGenresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GenreResponse>> {
        const response = await this.apiAdminGenresGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminGenresIdDeleteRaw(requestParameters: ApiAdminGenresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminGenresIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/genres/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminGenresIdDelete(requestParameters: ApiAdminGenresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminGenresIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminGenresIdPutRaw(requestParameters: ApiAdminGenresIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminGenresIdPut().'
            );
        }

        if (requestParameters['manageGenreRequest'] == null) {
            throw new runtime.RequiredError(
                'manageGenreRequest',
                'Required parameter "manageGenreRequest" was null or undefined when calling apiAdminGenresIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/genres/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ManageGenreRequestToJSON(requestParameters['manageGenreRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminGenresIdPut(requestParameters: ApiAdminGenresIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminGenresIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminGenresPostRaw(requestParameters: ApiAdminGenresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>> {
        if (requestParameters['manageGenreRequest'] == null) {
            throw new runtime.RequiredError(
                'manageGenreRequest',
                'Required parameter "manageGenreRequest" was null or undefined when calling apiAdminGenresPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/genres`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ManageGenreRequestToJSON(requestParameters['manageGenreRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminGenresPost(requestParameters: ApiAdminGenresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse> {
        const response = await this.apiAdminGenresPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
