/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IdResponse,
  ManageSeriesRequest,
  ProblemDetails,
  SeriesResponse,
} from '../models/index';
import {
    IdResponseFromJSON,
    IdResponseToJSON,
    ManageSeriesRequestFromJSON,
    ManageSeriesRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SeriesResponseFromJSON,
    SeriesResponseToJSON,
} from '../models/index';

export interface ApiAdminSeriesIdDeleteRequest {
    id: string;
}

export interface ApiAdminSeriesIdPutRequest {
    id: string;
    manageSeriesRequest: ManageSeriesRequest;
}

export interface ApiAdminSeriesPostRequest {
    manageSeriesRequest: ManageSeriesRequest;
}

/**
 * AdminSeriesApi - interface
 * 
 * @export
 * @interface AdminSeriesApiInterface
 */
export interface AdminSeriesApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminSeriesApiInterface
     */
    apiAdminSeriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeriesResponse>>>;

    /**
     */
    apiAdminSeriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeriesResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminSeriesApiInterface
     */
    apiAdminSeriesIdDeleteRaw(requestParameters: ApiAdminSeriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminSeriesIdDelete(requestParameters: ApiAdminSeriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {ManageSeriesRequest} manageSeriesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminSeriesApiInterface
     */
    apiAdminSeriesIdPutRaw(requestParameters: ApiAdminSeriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAdminSeriesIdPut(requestParameters: ApiAdminSeriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {ManageSeriesRequest} manageSeriesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminSeriesApiInterface
     */
    apiAdminSeriesPostRaw(requestParameters: ApiAdminSeriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     */
    apiAdminSeriesPost(requestParameters: ApiAdminSeriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse>;

}

/**
 * 
 */
export class AdminSeriesApi extends runtime.BaseAPI implements AdminSeriesApiInterface {

    /**
     */
    async apiAdminSeriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeriesResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/series`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SeriesResponseFromJSON));
    }

    /**
     */
    async apiAdminSeriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeriesResponse>> {
        const response = await this.apiAdminSeriesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminSeriesIdDeleteRaw(requestParameters: ApiAdminSeriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminSeriesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/admin/series/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminSeriesIdDelete(requestParameters: ApiAdminSeriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminSeriesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminSeriesIdPutRaw(requestParameters: ApiAdminSeriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdminSeriesIdPut().'
            );
        }

        if (requestParameters['manageSeriesRequest'] == null) {
            throw new runtime.RequiredError(
                'manageSeriesRequest',
                'Required parameter "manageSeriesRequest" was null or undefined when calling apiAdminSeriesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/series/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ManageSeriesRequestToJSON(requestParameters['manageSeriesRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminSeriesIdPut(requestParameters: ApiAdminSeriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminSeriesIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminSeriesPostRaw(requestParameters: ApiAdminSeriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>> {
        if (requestParameters['manageSeriesRequest'] == null) {
            throw new runtime.RequiredError(
                'manageSeriesRequest',
                'Required parameter "manageSeriesRequest" was null or undefined when calling apiAdminSeriesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/admin/series`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ManageSeriesRequestToJSON(requestParameters['manageSeriesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminSeriesPost(requestParameters: ApiAdminSeriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse> {
        const response = await this.apiAdminSeriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
