/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArcadeStatsResponse,
  LeaderboardResponse,
  ProblemDetails,
  SubmitScoreRequest,
} from '../models/index';
import {
    ArcadeStatsResponseFromJSON,
    ArcadeStatsResponseToJSON,
    LeaderboardResponseFromJSON,
    LeaderboardResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SubmitScoreRequestFromJSON,
    SubmitScoreRequestToJSON,
} from '../models/index';

export interface GetLeaderboardRequest {
    game?: string;
    take?: number;
}

export interface GetMyArcadeStatsRequest {
    game?: string;
}

export interface SubmitScoreOperationRequest {
    submitScoreRequest: SubmitScoreRequest;
}

/**
 * ArcadeApi - interface
 * 
 * @export
 * @interface ArcadeApiInterface
 */
export interface ArcadeApiInterface {
    /**
     * 
     * @param {string} [game] 
     * @param {number} [take] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArcadeApiInterface
     */
    getLeaderboardRaw(requestParameters: GetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardResponse>>;

    /**
     */
    getLeaderboard(requestParameters: GetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardResponse>;

    /**
     * 
     * @param {string} [game] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArcadeApiInterface
     */
    getMyArcadeStatsRaw(requestParameters: GetMyArcadeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArcadeStatsResponse>>;

    /**
     */
    getMyArcadeStats(requestParameters: GetMyArcadeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArcadeStatsResponse>;

    /**
     * 
     * @param {SubmitScoreRequest} submitScoreRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArcadeApiInterface
     */
    submitScoreRaw(requestParameters: SubmitScoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArcadeStatsResponse>>;

    /**
     */
    submitScore(requestParameters: SubmitScoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArcadeStatsResponse>;

}

/**
 * 
 */
export class ArcadeApi extends runtime.BaseAPI implements ArcadeApiInterface {

    /**
     */
    async getLeaderboardRaw(requestParameters: GetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaderboardResponse>> {
        const queryParameters: any = {};

        if (requestParameters['game'] != null) {
            queryParameters['game'] = requestParameters['game'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/arcade/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaderboardResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLeaderboard(requestParameters: GetLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaderboardResponse> {
        const response = await this.getLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyArcadeStatsRaw(requestParameters: GetMyArcadeStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArcadeStatsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['game'] != null) {
            queryParameters['game'] = requestParameters['game'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/arcade/scores/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArcadeStatsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMyArcadeStats(requestParameters: GetMyArcadeStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArcadeStatsResponse> {
        const response = await this.getMyArcadeStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async submitScoreRaw(requestParameters: SubmitScoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArcadeStatsResponse>> {
        if (requestParameters['submitScoreRequest'] == null) {
            throw new runtime.RequiredError(
                'submitScoreRequest',
                'Required parameter "submitScoreRequest" was null or undefined when calling submitScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/arcade/scores`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitScoreRequestToJSON(requestParameters['submitScoreRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArcadeStatsResponseFromJSON(jsonValue));
    }

    /**
     */
    async submitScore(requestParameters: SubmitScoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArcadeStatsResponse> {
        const response = await this.submitScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
