/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookAuthorResponse,
  BookCommentRequest,
  BookCommentResponse,
  BookDetailResponse,
  IdResponse,
  ProblemDetails,
  SetBookStatusRequest,
  ShelfCatalogResponse,
} from '../models/index';
import {
    BookAuthorResponseFromJSON,
    BookAuthorResponseToJSON,
    BookCommentRequestFromJSON,
    BookCommentRequestToJSON,
    BookCommentResponseFromJSON,
    BookCommentResponseToJSON,
    BookDetailResponseFromJSON,
    BookDetailResponseToJSON,
    IdResponseFromJSON,
    IdResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SetBookStatusRequestFromJSON,
    SetBookStatusRequestToJSON,
    ShelfCatalogResponseFromJSON,
    ShelfCatalogResponseToJSON,
} from '../models/index';

export interface ApiBooksAuthorsGetRequest {
    query?: string;
}

export interface ApiBooksGetRequest {
    genre?: string;
    author?: string;
    search?: string;
    sort?: string;
    offset?: number;
    limit?: number;
}

export interface ApiBooksIdCommentsGetRequest {
    id: string;
}

export interface ApiBooksIdCommentsPostRequest {
    id: string;
    bookCommentRequest: BookCommentRequest;
}

export interface ApiBooksIdStatusDeleteRequest {
    id: string;
}

export interface ApiBooksIdStatusPutRequest {
    id: string;
    setBookStatusRequest: SetBookStatusRequest;
}

export interface ApiBooksSlugGetRequest {
    slug: string;
}

/**
 * BooksApi - interface
 * 
 * @export
 * @interface BooksApiInterface
 */
export interface BooksApiInterface {
    /**
     * 
     * @param {string} [query] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksAuthorsGetRaw(requestParameters: ApiBooksAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookAuthorResponse>>>;

    /**
     */
    apiBooksAuthorsGet(requestParameters: ApiBooksAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookAuthorResponse>>;

    /**
     * 
     * @param {string} [genre] 
     * @param {string} [author] 
     * @param {string} [search] 
     * @param {string} [sort] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksGetRaw(requestParameters: ApiBooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShelfCatalogResponse>>;

    /**
     */
    apiBooksGet(requestParameters: ApiBooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShelfCatalogResponse>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksIdCommentsGetRaw(requestParameters: ApiBooksIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookCommentResponse>>>;

    /**
     */
    apiBooksIdCommentsGet(requestParameters: ApiBooksIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookCommentResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {BookCommentRequest} bookCommentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksIdCommentsPostRaw(requestParameters: ApiBooksIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     */
    apiBooksIdCommentsPost(requestParameters: ApiBooksIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksIdStatusDeleteRaw(requestParameters: ApiBooksIdStatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiBooksIdStatusDelete(requestParameters: ApiBooksIdStatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {SetBookStatusRequest} setBookStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksIdStatusPutRaw(requestParameters: ApiBooksIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiBooksIdStatusPut(requestParameters: ApiBooksIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApiInterface
     */
    apiBooksSlugGetRaw(requestParameters: ApiBooksSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookDetailResponse>>;

    /**
     */
    apiBooksSlugGet(requestParameters: ApiBooksSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookDetailResponse>;

}

/**
 * 
 */
export class BooksApi extends runtime.BaseAPI implements BooksApiInterface {

    /**
     */
    async apiBooksAuthorsGetRaw(requestParameters: ApiBooksAuthorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookAuthorResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books/authors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookAuthorResponseFromJSON));
    }

    /**
     */
    async apiBooksAuthorsGet(requestParameters: ApiBooksAuthorsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookAuthorResponse>> {
        const response = await this.apiBooksAuthorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBooksGetRaw(requestParameters: ApiBooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShelfCatalogResponse>> {
        const queryParameters: any = {};

        if (requestParameters['genre'] != null) {
            queryParameters['genre'] = requestParameters['genre'];
        }

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShelfCatalogResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBooksGet(requestParameters: ApiBooksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShelfCatalogResponse> {
        const response = await this.apiBooksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBooksIdCommentsGetRaw(requestParameters: ApiBooksIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookCommentResponse>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBooksIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books/{id}/comments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookCommentResponseFromJSON));
    }

    /**
     */
    async apiBooksIdCommentsGet(requestParameters: ApiBooksIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookCommentResponse>> {
        const response = await this.apiBooksIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBooksIdCommentsPostRaw(requestParameters: ApiBooksIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBooksIdCommentsPost().'
            );
        }

        if (requestParameters['bookCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'bookCommentRequest',
                'Required parameter "bookCommentRequest" was null or undefined when calling apiBooksIdCommentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/books/{id}/comments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookCommentRequestToJSON(requestParameters['bookCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBooksIdCommentsPost(requestParameters: ApiBooksIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdResponse> {
        const response = await this.apiBooksIdCommentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBooksIdStatusDeleteRaw(requestParameters: ApiBooksIdStatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBooksIdStatusDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiBooksIdStatusDelete(requestParameters: ApiBooksIdStatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBooksIdStatusDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiBooksIdStatusPutRaw(requestParameters: ApiBooksIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBooksIdStatusPut().'
            );
        }

        if (requestParameters['setBookStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'setBookStatusRequest',
                'Required parameter "setBookStatusRequest" was null or undefined when calling apiBooksIdStatusPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/books/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetBookStatusRequestToJSON(requestParameters['setBookStatusRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiBooksIdStatusPut(requestParameters: ApiBooksIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBooksIdStatusPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiBooksSlugGetRaw(requestParameters: ApiBooksSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookDetailResponse>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBooksSlugGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBooksSlugGet(requestParameters: ApiBooksSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookDetailResponse> {
        const response = await this.apiBooksSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
