/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookCommentRequest,
  ProblemDetails,
} from '../models/index';
import {
    BookCommentRequestFromJSON,
    BookCommentRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiBookCommentsIdDeleteRequest {
    id: string;
}

export interface ApiBookCommentsIdPutRequest {
    id: string;
    bookCommentRequest: BookCommentRequest;
}

/**
 * BookCommentsApi - interface
 * 
 * @export
 * @interface BookCommentsApiInterface
 */
export interface BookCommentsApiInterface {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookCommentsApiInterface
     */
    apiBookCommentsIdDeleteRaw(requestParameters: ApiBookCommentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiBookCommentsIdDelete(requestParameters: ApiBookCommentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {BookCommentRequest} bookCommentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookCommentsApiInterface
     */
    apiBookCommentsIdPutRaw(requestParameters: ApiBookCommentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiBookCommentsIdPut(requestParameters: ApiBookCommentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class BookCommentsApi extends runtime.BaseAPI implements BookCommentsApiInterface {

    /**
     */
    async apiBookCommentsIdDeleteRaw(requestParameters: ApiBookCommentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBookCommentsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/book-comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiBookCommentsIdDelete(requestParameters: ApiBookCommentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBookCommentsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiBookCommentsIdPutRaw(requestParameters: ApiBookCommentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBookCommentsIdPut().'
            );
        }

        if (requestParameters['bookCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'bookCommentRequest',
                'Required parameter "bookCommentRequest" was null or undefined when calling apiBookCommentsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/book-comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookCommentRequestToJSON(requestParameters['bookCommentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiBookCommentsIdPut(requestParameters: ApiBookCommentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBookCommentsIdPutRaw(requestParameters, initOverrides);
    }

}
