/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenreResponse,
  ProblemDetails,
} from '../models/index';
import {
    GenreResponseFromJSON,
    GenreResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

/**
 * GenresApi - interface
 * 
 * @export
 * @interface GenresApiInterface
 */
export interface GenresApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenresApiInterface
     */
    apiGenresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GenreResponse>>>;

    /**
     */
    apiGenresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GenreResponse>>;

}

/**
 * 
 */
export class GenresApi extends runtime.BaseAPI implements GenresApiInterface {

    /**
     */
    async apiGenresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GenreResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/genres`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreResponseFromJSON));
    }

    /**
     */
    async apiGenresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GenreResponse>> {
        const response = await this.apiGenresGetRaw(initOverrides);
        return await response.value();
    }

}
