/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  SeriesDetailResponse,
  SeriesResponse,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SeriesDetailResponseFromJSON,
    SeriesDetailResponseToJSON,
    SeriesResponseFromJSON,
    SeriesResponseToJSON,
} from '../models/index';

export interface ApiSeriesSlugGetRequest {
    slug: string;
}

/**
 * SeriesApi - interface
 * 
 * @export
 * @interface SeriesApiInterface
 */
export interface SeriesApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeriesApiInterface
     */
    apiSeriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeriesResponse>>>;

    /**
     */
    apiSeriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeriesResponse>>;

    /**
     * 
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeriesApiInterface
     */
    apiSeriesSlugGetRaw(requestParameters: ApiSeriesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeriesDetailResponse>>;

    /**
     */
    apiSeriesSlugGet(requestParameters: ApiSeriesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeriesDetailResponse>;

}

/**
 * 
 */
export class SeriesApi extends runtime.BaseAPI implements SeriesApiInterface {

    /**
     */
    async apiSeriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeriesResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/series`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SeriesResponseFromJSON));
    }

    /**
     */
    async apiSeriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeriesResponse>> {
        const response = await this.apiSeriesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSeriesSlugGetRaw(requestParameters: ApiSeriesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeriesDetailResponse>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiSeriesSlugGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/series/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeriesDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSeriesSlugGet(requestParameters: ApiSeriesSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeriesDetailResponse> {
        const response = await this.apiSeriesSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
