/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HomeStatsResponse,
  ProblemDetails,
} from '../models/index';
import {
    HomeStatsResponseFromJSON,
    HomeStatsResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

/**
 * StatsApi - interface
 * 
 * @export
 * @interface StatsApiInterface
 */
export interface StatsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getHomeStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HomeStatsResponse>>;

    /**
     */
    getHomeStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HomeStatsResponse>;

}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI implements StatsApiInterface {

    /**
     */
    async getHomeStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HomeStatsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HomeStatsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getHomeStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HomeStatsResponse> {
        const response = await this.getHomeStatsRaw(initOverrides);
        return await response.value();
    }

}
