/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.Blog.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  ShelfCatalogResponse,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ShelfCatalogResponseFromJSON,
    ShelfCatalogResponseToJSON,
} from '../models/index';

export interface ApiUsersUsernameShelfGetRequest {
    username: string;
    status?: string;
    genre?: string;
    search?: string;
    sort?: string;
    offset?: number;
    limit?: number;
}

/**
 * UserShelfApi - interface
 * 
 * @export
 * @interface UserShelfApiInterface
 */
export interface UserShelfApiInterface {
    /**
     * 
     * @param {string} username 
     * @param {string} [status] 
     * @param {string} [genre] 
     * @param {string} [search] 
     * @param {string} [sort] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserShelfApiInterface
     */
    apiUsersUsernameShelfGetRaw(requestParameters: ApiUsersUsernameShelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShelfCatalogResponse>>;

    /**
     */
    apiUsersUsernameShelfGet(requestParameters: ApiUsersUsernameShelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShelfCatalogResponse>;

}

/**
 * 
 */
export class UserShelfApi extends runtime.BaseAPI implements UserShelfApiInterface {

    /**
     */
    async apiUsersUsernameShelfGetRaw(requestParameters: ApiUsersUsernameShelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShelfCatalogResponse>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling apiUsersUsernameShelfGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['genre'] != null) {
            queryParameters['genre'] = requestParameters['genre'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/users/{username}/shelf`.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShelfCatalogResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiUsersUsernameShelfGet(requestParameters: ApiUsersUsernameShelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShelfCatalogResponse> {
        const response = await this.apiUsersUsernameShelfGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
