/* tslint:disable */
/* eslint-disable */
/**
 * Lazy.App | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentResponse,
  CreatePostRequest,
  NoContent,
  PostDetailedResponse,
  PostResponse,
  ProblemDetails,
  PublishedPostResponse,
  UpdatePostRequest,
  UserPostResponse,
  VoteDirection,
} from '../models/index';
import {
    CommentResponseFromJSON,
    CommentResponseToJSON,
    CreatePostRequestFromJSON,
    CreatePostRequestToJSON,
    NoContentFromJSON,
    NoContentToJSON,
    PostDetailedResponseFromJSON,
    PostDetailedResponseToJSON,
    PostResponseFromJSON,
    PostResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    PublishedPostResponseFromJSON,
    PublishedPostResponseToJSON,
    UpdatePostRequestFromJSON,
    UpdatePostRequestToJSON,
    UserPostResponseFromJSON,
    UserPostResponseToJSON,
    VoteDirectionFromJSON,
    VoteDirectionToJSON,
} from '../models/index';

export interface ApiPostsGetRequest {
    offset?: number;
}

export interface ApiPostsIdCommentsGetRequest {
    id: string;
}

export interface ApiPostsIdCountViewPutRequest {
    id: string;
}

export interface ApiPostsIdDeleteRequest {
    id: string;
}

export interface ApiPostsIdGetRequest {
    id: string;
}

export interface ApiPostsIdHidePutRequest {
    id: string;
}

export interface ApiPostsIdPublishPutRequest {
    id: string;
}

export interface ApiPostsIdPutRequest {
    id: string;
    updatePostRequest: UpdatePostRequest;
}

export interface ApiPostsIdVotePutRequest {
    id: string;
    direction?: VoteDirection;
}

export interface ApiPostsPostRequest {
    createPostRequest: CreatePostRequest;
}

export interface ApiPostsSlugGetRequest {
    slug: string;
}

export interface ApiPostsTTagGetRequest {
    tag: string;
}

export interface ApiPostsUserNamePostsGetRequest {
    userName: string;
    offset?: number;
}

/**
 * PostsApi - interface
 * 
 * @export
 * @interface PostsApiInterface
 */
export interface PostsApiInterface {
    /**
     * 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsGetRaw(requestParameters: ApiPostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublishedPostResponse>>>;

    /**
     */
    apiPostsGet(requestParameters: ApiPostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublishedPostResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdCommentsGetRaw(requestParameters: ApiPostsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentResponse>>>;

    /**
     */
    apiPostsIdCommentsGet(requestParameters: ApiPostsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentResponse>>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdCountViewPutRaw(requestParameters: ApiPostsIdCountViewPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsIdCountViewPut(requestParameters: ApiPostsIdCountViewPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdDeleteRaw(requestParameters: ApiPostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsIdDelete(requestParameters: ApiPostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdGetRaw(requestParameters: ApiPostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostResponse>>;

    /**
     */
    apiPostsIdGet(requestParameters: ApiPostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostResponse>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdHidePutRaw(requestParameters: ApiPostsIdHidePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsIdHidePut(requestParameters: ApiPostsIdHidePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdPublishPutRaw(requestParameters: ApiPostsIdPublishPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsIdPublishPut(requestParameters: ApiPostsIdPublishPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {UpdatePostRequest} updatePostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdPutRaw(requestParameters: ApiPostsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsIdPut(requestParameters: ApiPostsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {VoteDirection} [direction] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsIdVotePutRaw(requestParameters: ApiPostsIdVotePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoContent>>;

    /**
     */
    apiPostsIdVotePut(requestParameters: ApiPostsIdVotePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoContent>;

    /**
     * 
     * @param {CreatePostRequest} createPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsPostRaw(requestParameters: ApiPostsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPostsPost(requestParameters: ApiPostsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsSlugGetRaw(requestParameters: ApiPostsSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetailedResponse>>;

    /**
     */
    apiPostsSlugGet(requestParameters: ApiPostsSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetailedResponse>;

    /**
     * 
     * @param {string} tag 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsTTagGetRaw(requestParameters: ApiPostsTTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublishedPostResponse>>>;

    /**
     */
    apiPostsTTagGet(requestParameters: ApiPostsTTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublishedPostResponse>>;

    /**
     * 
     * @param {string} userName 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    apiPostsUserNamePostsGetRaw(requestParameters: ApiPostsUserNamePostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPostResponse>>;

    /**
     */
    apiPostsUserNamePostsGet(requestParameters: ApiPostsUserNamePostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPostResponse>;

}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI implements PostsApiInterface {

    /**
     */
    async apiPostsGetRaw(requestParameters: ApiPostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublishedPostResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublishedPostResponseFromJSON));
    }

    /**
     */
    async apiPostsGet(requestParameters: ApiPostsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublishedPostResponse>> {
        const response = await this.apiPostsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsIdCommentsGetRaw(requestParameters: ApiPostsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentResponse>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}/comments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentResponseFromJSON));
    }

    /**
     */
    async apiPostsIdCommentsGet(requestParameters: ApiPostsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentResponse>> {
        const response = await this.apiPostsIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsIdCountViewPutRaw(requestParameters: ApiPostsIdCountViewPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdCountViewPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}/count-view`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsIdCountViewPut(requestParameters: ApiPostsIdCountViewPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsIdCountViewPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsIdDeleteRaw(requestParameters: ApiPostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsIdDelete(requestParameters: ApiPostsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsIdGetRaw(requestParameters: ApiPostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostsIdGet(requestParameters: ApiPostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostResponse> {
        const response = await this.apiPostsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsIdHidePutRaw(requestParameters: ApiPostsIdHidePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdHidePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}/hide`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsIdHidePut(requestParameters: ApiPostsIdHidePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsIdHidePutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsIdPublishPutRaw(requestParameters: ApiPostsIdPublishPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdPublishPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}/publish`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsIdPublishPut(requestParameters: ApiPostsIdPublishPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsIdPublishPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsIdPutRaw(requestParameters: ApiPostsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdPut().'
            );
        }

        if (requestParameters['updatePostRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePostRequest',
                'Required parameter "updatePostRequest" was null or undefined when calling apiPostsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePostRequestToJSON(requestParameters['updatePostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsIdPut(requestParameters: ApiPostsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsIdVotePutRaw(requestParameters: ApiPostsIdVotePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoContent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPostsIdVotePut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{id}/vote`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NoContentFromJSON(jsonValue));
    }

    /**
     */
    async apiPostsIdVotePut(requestParameters: ApiPostsIdVotePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoContent> {
        const response = await this.apiPostsIdVotePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsPostRaw(requestParameters: ApiPostsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createPostRequest',
                'Required parameter "createPostRequest" was null or undefined when calling apiPostsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/posts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostRequestToJSON(requestParameters['createPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPostsPost(requestParameters: ApiPostsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPostsSlugGetRaw(requestParameters: ApiPostsSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetailedResponse>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiPostsSlugGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailedResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostsSlugGet(requestParameters: ApiPostsSlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetailedResponse> {
        const response = await this.apiPostsSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsTTagGetRaw(requestParameters: ApiPostsTTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublishedPostResponse>>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling apiPostsTTagGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/t/{tag}`.replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublishedPostResponseFromJSON));
    }

    /**
     */
    async apiPostsTTagGet(requestParameters: ApiPostsTTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublishedPostResponse>> {
        const response = await this.apiPostsTTagGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPostsUserNamePostsGetRaw(requestParameters: ApiPostsUserNamePostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPostResponse>> {
        if (requestParameters['userName'] == null) {
            throw new runtime.RequiredError(
                'userName',
                'Required parameter "userName" was null or undefined when calling apiPostsUserNamePostsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/posts/{userName}/posts`.replace(`{${"userName"}}`, encodeURIComponent(String(requestParameters['userName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPostResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPostsUserNamePostsGet(requestParameters: ApiPostsUserNamePostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPostResponse> {
        const response = await this.apiPostsUserNamePostsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
