/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCommentRequest
 */
export interface AddCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    postId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCommentRequest
     */
    body?: string | null;
}

/**
 * Check if a given object implements the AddCommentRequest interface.
 */
export function instanceOfAddCommentRequest(value: object): value is AddCommentRequest {
    return true;
}

export function AddCommentRequestFromJSON(json: any): AddCommentRequest {
    return AddCommentRequestFromJSONTyped(json, false);
}

export function AddCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'] == null ? undefined : json['postId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function AddCommentRequestToJSON(value?: AddCommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'postId': value['postId'],
        'userId': value['userId'],
        'body': value['body'],
    };
}

