/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentResponse } from './CommentResponse';
import {
    CommentResponseFromJSON,
    CommentResponseFromJSONTyped,
    CommentResponseToJSON,
} from './CommentResponse';

/**
 * 
 * @export
 * @interface CommentResponseListResult
 */
export interface CommentResponseListResult {
    /**
     * 
     * @type {boolean}
     * @memberof CommentResponseListResult
     */
    readonly isSuccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommentResponseListResult
     */
    readonly isFailure?: boolean;
    /**
     * 
     * @type {Error}
     * @memberof CommentResponseListResult
     */
    error?: Error;
    /**
     * 
     * @type {Array<CommentResponse>}
     * @memberof CommentResponseListResult
     */
    readonly value?: Array<CommentResponse> | null;
}

/**
 * Check if a given object implements the CommentResponseListResult interface.
 */
export function instanceOfCommentResponseListResult(value: object): value is CommentResponseListResult {
    return true;
}

export function CommentResponseListResultFromJSON(json: any): CommentResponseListResult {
    return CommentResponseListResultFromJSONTyped(json, false);
}

export function CommentResponseListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponseListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'isFailure': json['isFailure'] == null ? undefined : json['isFailure'],
        'error': json['error'] == null ? undefined : json['error'],
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(CommentResponseFromJSON)),
    };
}

export function CommentResponseListResultToJSON(value?: Omit<CommentResponseListResult, 'isSuccess'|'isFailure'|'value'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

