/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    id?: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof CommentResponse
     */
    user?: UserResponse;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    userAvatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    body?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CommentResponse
     */
    createdAtUtc?: Date;
}

/**
 * Check if a given object implements the CommentResponse interface.
 */
export function instanceOfCommentResponse(value: object): value is CommentResponse {
    return true;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'user': json['user'] == null ? undefined : UserResponseFromJSON(json['user']),
        'userAvatarUrl': json['userAvatarUrl'] == null ? undefined : json['userAvatarUrl'],
        'body': json['body'] == null ? undefined : json['body'],
        'createdAtUtc': json['createdAtUtc'] == null ? undefined : (new Date(json['createdAtUtc'])),
    };
}

export function CommentResponseToJSON(value?: CommentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'user': UserResponseToJSON(value['user']),
        'userAvatarUrl': value['userAvatarUrl'],
        'body': value['body'],
        'createdAtUtc': value['createdAtUtc'] == null ? undefined : ((value['createdAtUtc']).toISOString()),
    };
}

