/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetailedResponse } from './PostDetailedResponse';
import {
    PostDetailedResponseFromJSON,
    PostDetailedResponseFromJSONTyped,
    PostDetailedResponseToJSON,
} from './PostDetailedResponse';

/**
 * 
 * @export
 * @interface PostDetailedResponseResult
 */
export interface PostDetailedResponseResult {
    /**
     * 
     * @type {boolean}
     * @memberof PostDetailedResponseResult
     */
    readonly isSuccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostDetailedResponseResult
     */
    readonly isFailure?: boolean;
    /**
     * 
     * @type {Error}
     * @memberof PostDetailedResponseResult
     */
    error?: Error;
    /**
     * 
     * @type {PostDetailedResponse}
     * @memberof PostDetailedResponseResult
     */
    value?: PostDetailedResponse;
}

/**
 * Check if a given object implements the PostDetailedResponseResult interface.
 */
export function instanceOfPostDetailedResponseResult(value: object): value is PostDetailedResponseResult {
    return true;
}

export function PostDetailedResponseResultFromJSON(json: any): PostDetailedResponseResult {
    return PostDetailedResponseResultFromJSONTyped(json, false);
}

export function PostDetailedResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetailedResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'isFailure': json['isFailure'] == null ? undefined : json['isFailure'],
        'error': json['error'] == null ? undefined : json['error'],
        'value': json['value'] == null ? undefined : PostDetailedResponseFromJSON(json['value']),
    };
}

export function PostDetailedResponseResultToJSON(value?: Omit<PostDetailedResponseResult, 'isSuccess'|'isFailure'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
        'value': PostDetailedResponseToJSON(value['value']),
    };
}

