/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostResponse } from './PostResponse';
import {
    PostResponseFromJSON,
    PostResponseFromJSONTyped,
    PostResponseToJSON,
} from './PostResponse';

/**
 * 
 * @export
 * @interface PostResponseResult
 */
export interface PostResponseResult {
    /**
     * 
     * @type {boolean}
     * @memberof PostResponseResult
     */
    readonly isSuccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostResponseResult
     */
    readonly isFailure?: boolean;
    /**
     * 
     * @type {Error}
     * @memberof PostResponseResult
     */
    error?: Error;
    /**
     * 
     * @type {PostResponse}
     * @memberof PostResponseResult
     */
    value?: PostResponse;
}

/**
 * Check if a given object implements the PostResponseResult interface.
 */
export function instanceOfPostResponseResult(value: object): value is PostResponseResult {
    return true;
}

export function PostResponseResultFromJSON(json: any): PostResponseResult {
    return PostResponseResultFromJSONTyped(json, false);
}

export function PostResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'isFailure': json['isFailure'] == null ? undefined : json['isFailure'],
        'error': json['error'] == null ? undefined : json['error'],
        'value': json['value'] == null ? undefined : PostResponseFromJSON(json['value']),
    };
}

export function PostResponseResultToJSON(value?: Omit<PostResponseResult, 'isSuccess'|'isFailure'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
        'value': PostResponseToJSON(value['value']),
    };
}

