/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagResponse } from './TagResponse';
import {
    TagResponseFromJSON,
    TagResponseFromJSONTyped,
    TagResponseToJSON,
} from './TagResponse';

/**
 * 
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    body?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    slug?: string | null;
    /**
     * 
     * @type {Array<TagResponse>}
     * @memberof PostResponse
     */
    tags?: Array<TagResponse> | null;
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    coverUrl?: string | null;
}

/**
 * Check if a given object implements the PostResponse interface.
 */
export function instanceOfPostResponse(value: object): value is PostResponse {
    return true;
}

export function PostResponseFromJSON(json: any): PostResponse {
    return PostResponseFromJSONTyped(json, false);
}

export function PostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'body': json['body'] == null ? undefined : json['body'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagResponseFromJSON)),
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
    };
}

export function PostResponseToJSON(value?: PostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'body': value['body'],
        'slug': value['slug'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagResponseToJSON)),
        'coverUrl': value['coverUrl'],
    };
}

