/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserRequest
 */
export interface RegisterUserRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserRequest
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserRequest
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserRequest
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the RegisterUserRequest interface.
 */
export function instanceOfRegisterUserRequest(value: object): value is RegisterUserRequest {
    return true;
}

export function RegisterUserRequestFromJSON(json: any): RegisterUserRequest {
    return RegisterUserRequestFromJSONTyped(json, false);
}

export function RegisterUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function RegisterUserRequestToJSON(value?: RegisterUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'userName': value['userName'],
        'password': value['password'],
    };
}

