/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';
import type { UserPostItem } from './UserPostItem';
import {
    UserPostItemFromJSON,
    UserPostItemFromJSONTyped,
    UserPostItemToJSON,
} from './UserPostItem';

/**
 * 
 * @export
 * @interface UserPostResponse
 */
export interface UserPostResponse {
    /**
     * 
     * @type {UserResponse}
     * @memberof UserPostResponse
     */
    user?: UserResponse;
    /**
     * 
     * @type {Array<UserPostItem>}
     * @memberof UserPostResponse
     */
    postItems?: Array<UserPostItem> | null;
}

/**
 * Check if a given object implements the UserPostResponse interface.
 */
export function instanceOfUserPostResponse(value: object): value is UserPostResponse {
    return true;
}

export function UserPostResponseFromJSON(json: any): UserPostResponse {
    return UserPostResponseFromJSONTyped(json, false);
}

export function UserPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserResponseFromJSON(json['user']),
        'postItems': json['postItems'] == null ? undefined : ((json['postItems'] as Array<any>).map(UserPostItemFromJSON)),
    };
}

export function UserPostResponseToJSON(value?: UserPostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserResponseToJSON(value['user']),
        'postItems': value['postItems'] == null ? undefined : ((value['postItems'] as Array<any>).map(UserPostItemToJSON)),
    };
}

